### ISSUE TITLE
support for OpenWrt 18.06.1 

### ISSUE THREAD

**Issue by gybiscus** [milaq/openwrt_knockd#4]
Any chances to support subj?
During build for target of Linksys wrt3200acm make install failed
Thanks

**Comment by JernejL** [comment]
I'm another interested person in this, i'll be grateful if any work can be done towards this.

**Comment by TDFKAOlli** [comment]
Yep, would be interested too. I tried to change the OpenWRT makefile to fetch the latest knockd from git, but I seem to fail finding the right syntax and didn't had time to dive into it.

**Comment by TDFKAOlli** [comment]
Yep, would be interested too. I tried to change the OpenWRT makefile to fetch the latest knockd from git, but I seem to fail finding the right syntax and didn't had time to dive into it.

**Comment by TDFKAOlli** [comment]
Just tried to build with OpenWRT 18.06.1 and although the install step seems to fail, the package is there in bin/packages/mips_24kc/base/. 
For me also the configure step seem to fail. Maybe something changed in the build system of OpenWRT regarding those steps. Anyhow as the package is there, done by the compile step, so you can continue with that package.

**Comment by TDFKAOlli** [comment]
Last but not least, the updated documentation on creating packages in OpenWrt now helped changing the makefile to fetch the actual version of knockd from git. (Well, actual version means end of 2015). But hope is it will be continued by someone else.
I will create a pull request and then try to get the IPv6 patches and other stuff applied from jvinet/knock (https://github.com/jvinet/knock).
And as a note, the "install" command seems not present anymore. The compile step also installs and creates the .ipk-package. As such the description needs to be adapted. I managed to get it build by:
make package/knockd/clean
make package/knockd/download
make package/knockd/compile

**Comment by JernejL** [comment]
I wish to test the build too, can i get a built binary so i can test it on TP-Link TL-WR1043N/ND v1

**Comment by TDFKAOlli** [comment]
Here the package for TL-WR1043N/ND v1:
[https://github.com/TDFKAOlli/openwrt_knockd/releases/download/0.7.8-2_v18.06.1-prelim2/knockd_0.7.8-2_mips_24kc.zip](url)
Build from my prelim branch. In the end if would be cleaner to wait milaq to pull, but anyway for testing it might be fine.

**Comment by milaq** [comment]
fixed by https://github.com/milaq/openwrt_knockd/commit/015ef836208cee45713d28f6fa0bd00362272d96
